"""baseline schema

Revision ID: 913259aa108b
Revises: 
Create Date: 2026-09-17 14:24:48.119754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913259aa108b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_pending_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_pending_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_pending_actions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_pending_actions_status'), ['status'], unique=False)

    op.create_table('agent_runs',
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('retrieval_stats', sa.JSON(), nullable=True),
    sa.Column('model_usage', sa.JSON(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('runtime_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_session_id'), ['session_id'], unique=False)

    op.create_table('answer_feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_snapshot', sa.Text(), nullable=False),
    sa.Column('retrieval_snapshot', sa.JSON(), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('target_page_id', sa.String(length=36), nullable=True),
    sa.Column('external_research_run_id', sa.String(length=36), nullable=True),
    sa.Column('pending_action_id', sa.String(length=36), nullable=True),
    sa.Column('draft_title', sa.String(length=255), nullable=True),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('write_result', sa.JSON(), nullable=True),
    sa.Column('index_result', sa.JSON(), nullable=True),
    sa.Column('retest_request_id', sa.String(length=128), nullable=True),
    sa.Column('retest_answer', sa.Text(), nullable=True),
    sa.Column('retest_snapshot', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', name='uq_answer_feedback_request')
    )
    with op.batch_alter_table('answer_feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_feedbacks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_feedbacks_external_research_run_id'), ['external_research_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_feedbacks_pending_action_id'), ['pending_action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_feedbacks_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_feedbacks_retest_request_id'), ['retest_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_feedbacks_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_feedbacks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_feedbacks_target_page_id'), ['target_page_id'], unique=False)

    op.create_table('audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('transcription_segments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audios_filename'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_audios_id'), ['id'], unique=False)

    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_messages_session_id'), ['session_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_message_id', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_session_id'), ['session_id'], unique=True)

    op.create_table('retrievals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('query_embedding', sa.Text(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('similarity_scores', sa.JSON(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('used_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retrievals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrievals_id'), ['id'], unique=False)

    op.create_table('wiki_index_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wiki_index_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_index_tasks_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_index_tasks_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_index_tasks_status'), ['status'], unique=False)

    op.create_table('wiki_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notebook', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_uri', sa.String(length=1024), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('index_status', sa.String(length=32), nullable=False),
    sa.Column('index_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wiki_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_pages_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_pages_index_status'), ['index_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_pages_notebook'), ['notebook'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_pages_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_pages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_pages_title'), ['title'], unique=False)
        batch_op.create_index('uq_wiki_pages_file_path', ['file_path'], unique=True, mysql_length=700)

    op.create_table('external_research_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('search_queries', sa.JSON(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('draft_title', sa.String(length=255), nullable=True),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_research_runs_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_research_runs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_research_runs_status'), ['status'], unique=False)

    op.create_table('wiki_page_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_page_id', sa.String(length=36), nullable=False),
    sa.Column('target_page_id', sa.String(length=36), nullable=True),
    sa.Column('target_title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_page_id'], ['wiki_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_page_id'], ['wiki_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_page_id', 'target_title', name='uq_wiki_page_link_target_title')
    )
    with op.batch_alter_table('wiki_page_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_page_links_source_page_id'), ['source_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_page_links_target_page_id'), ['target_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_page_links_target_title'), ['target_title'], unique=False)

    op.create_table('wiki_page_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_metadata', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'revision', name='uq_wiki_page_revision')
    )
    with op.batch_alter_table('wiki_page_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_page_revisions_page_id'), ['page_id'], unique=False)

    op.create_table('external_research_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['external_research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_research_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_research_sources_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_research_sources_run_id'), ['run_id'], unique=False)
        batch_op.create_index('uq_external_research_source_url', ['run_id', 'url'], unique=True, mysql_length={'url': 700})

    op.create_table('wiki_page_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('research_source_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_source_id'], ['external_research_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'research_source_id', name='uq_wiki_page_source')
    )
    with op.batch_alter_table('wiki_page_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wiki_page_sources_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_page_sources_research_source_id'), ['research_source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wiki_page_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_sources_research_source_id'))
        batch_op.drop_index(batch_op.f('ix_wiki_page_sources_page_id'))

    op.drop_table('wiki_page_sources')
    with op.batch_alter_table('external_research_sources', schema=None) as batch_op:
        batch_op.drop_index('uq_external_research_source_url', mysql_length={'url': 700})
        batch_op.drop_index(batch_op.f('ix_external_research_sources_run_id'))
        batch_op.drop_index(batch_op.f('ix_external_research_sources_content_hash'))

    op.drop_table('external_research_sources')
    with op.batch_alter_table('wiki_page_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_revisions_page_id'))

    op.drop_table('wiki_page_revisions')
    with op.batch_alter_table('wiki_page_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_page_links_target_title'))
        batch_op.drop_index(batch_op.f('ix_wiki_page_links_target_page_id'))
        batch_op.drop_index(batch_op.f('ix_wiki_page_links_source_page_id'))

    op.drop_table('wiki_page_links')
    with op.batch_alter_table('external_research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_research_runs_status'))
        batch_op.drop_index(batch_op.f('ix_external_research_runs_session_id'))
        batch_op.drop_index(batch_op.f('ix_external_research_runs_page_id'))

    op.drop_table('external_research_runs')
    with op.batch_alter_table('wiki_pages', schema=None) as batch_op:
        batch_op.drop_index('uq_wiki_pages_file_path', mysql_length=700)
        batch_op.drop_index(batch_op.f('ix_wiki_pages_title'))
        batch_op.drop_index(batch_op.f('ix_wiki_pages_status'))
        batch_op.drop_index(batch_op.f('ix_wiki_pages_source_type'))
        batch_op.drop_index(batch_op.f('ix_wiki_pages_notebook'))
        batch_op.drop_index(batch_op.f('ix_wiki_pages_index_status'))
        batch_op.drop_index(batch_op.f('ix_wiki_pages_content_hash'))

    op.drop_table('wiki_pages')
    with op.batch_alter_table('wiki_index_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_index_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_wiki_index_tasks_page_id'))
        batch_op.drop_index(batch_op.f('ix_wiki_index_tasks_next_attempt_at'))

    op.drop_table('wiki_index_tasks')
    with op.batch_alter_table('retrievals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retrievals_id'))

    op.drop_table('retrievals')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_messages_id'))

    op.drop_table('conversation_messages')
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audios_id'))
        batch_op.drop_index(batch_op.f('ix_audios_filename'))

    op.drop_table('audios')
    with op.batch_alter_table('answer_feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_feedbacks_target_page_id'))
        batch_op.drop_index(batch_op.f('ix_answer_feedbacks_status'))
        batch_op.drop_index(batch_op.f('ix_answer_feedbacks_session_id'))
        batch_op.drop_index(batch_op.f('ix_answer_feedbacks_retest_request_id'))
        batch_op.drop_index(batch_op.f('ix_answer_feedbacks_request_id'))
        batch_op.drop_index(batch_op.f('ix_answer_feedbacks_pending_action_id'))
        batch_op.drop_index(batch_op.f('ix_answer_feedbacks_external_research_run_id'))
        batch_op.drop_index(batch_op.f('ix_answer_feedbacks_category'))

    op.drop_table('answer_feedbacks')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_session_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('agent_pending_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_pending_actions_status'))
        batch_op.drop_index(batch_op.f('ix_agent_pending_actions_session_id'))

    op.drop_table('agent_pending_actions')
    # ### end Alembic commands ###
